Repository PrefectHQ/prefect-ui-library, pull requests merged in 2024-05, with the labels that each got.

#2342 Sync value between form and json when entering flow parameters
  src/automations/components/AutomationActionRunDeploymentParameters.vue
  src/components/DeploymentFormV2.vue
  src/components/FlowRunCreateFormV2.vue
  src/components/QuickRunParametersModal.vue
  src/schemas/components/SchemaForm.vue
  src/schemas/components/SchemaFormProperty.vue
  src/schemas/components/SchemaFormPropertyAllOf.vue
  src/schemas/components/SchemaFormPropertyAnyOf.vue
  src/schemas/components/SchemaFormPropertyArrayItem.vue
  src/schemas/components/SchemaFormPropertyArrayList.vue
  src/schemas/components/SchemaFormPropertyKindJson.vue
  src/schemas/components/SchemaInput.vue
  src/schemas/compositions/usePrefectKind.ts
  src/schemas/compositions/usePrefectKindValue.ts
  src/schemas/compositions/useSchema.ts
  src/schemas/compositions/useSchemaPropertyInput.ts
  src/schemas/compositions/useSchemaValidation.ts
  src/schemas/index.ts
  src/schemas/maps/schemaValue.ts
  src/schemas/types/schemaValues.ts
  src/services/WorkspaceSchemasWorkspaceApi.ts
  src/utilities/inject.ts
  src/utilities/json.ts
  src/utilities/reactivity.ts
Labels: DO NOT MERGE

#2351 Move over flow run state trigger from oss
  src/automations/components/AutomationTriggerEventInput.vue
  src/automations/components/AutomationTriggerFlowRunStateInput.vue
  src/automations/maps/flowRunStateTrigger.ts
  src/automations/types/flowRunStateTrigger.ts
  src/automations/types/index.ts
  src/maps/index.ts
Labels: maintenance

#2353 Move work pool status trigger and some remaining flow run state trigger code
  src/automations/components/AutomationTriggerEventInput.vue
  src/automations/components/AutomationTriggerWorkPoolStatusInput.vue
  src/automations/maps/workPoolStatusTrigger.ts
  src/automations/types/flowRunStateTrigger.ts
  src/automations/types/index.ts
  src/automations/types/workPoolStatusTrigger.ts
  src/components/WorkPoolStatusSelect.vue
  src/components/index.ts
  src/maps/index.ts
  src/maps/workPoolStatus.ts
  src/mocks/workPoolStatus.ts
  src/models/WorkPool.ts
  src/models/WorkPoolStatus.ts
  src/models/api/WorkPoolResponse.ts
Labels: maintenance

#2355 Fix parameters that are unions with default values that are unresponsive and disappear
  src/schemas/components/SchemaFormProperty.vue
  src/schemas/components/SchemaFormPropertyAnyOf.vue
Labels: fix

#2361 Move work queue status trigger from cloud
  src/automations/components/AutomationTriggerEventInput.vue
  src/automations/components/AutomationTriggerWorkQueueStatusInput.vue
  src/automations/maps/workQueueStatusTrigger.ts
  src/automations/types/index.ts
  src/automations/types/workQueueStatusTrigger.ts
  src/components/WorkQueueStatusSelect.vue
  src/components/index.ts
  src/maps/index.ts
Labels: maintenance

#2363 Add the do nothing option for automation actions
  src/automations/components/AutomationActionDescription.vue
  src/automations/components/AutomationActionInput.vue
  src/automations/maps/actions.ts
  src/automations/types/actions.ts
  src/automations/types/api/actions.ts
Labels: maintenance

#2367 Move over events apis from cloud
  src/automations/maps/utilities.ts
  src/automations/types/api/triggers.ts
  src/automations/types/flowRunStateTrigger.ts
  src/maps/index.ts
  src/maps/workspaceEvent.ts
  src/maps/workspaceEvents.ts
  src/maps/workspaceEventsCount.ts
  src/maps/workspaceEventsFilter.ts
  src/maps/workspaceEventsHistory.ts
  src/models/api/workspaceEvents.ts
  src/models/api/workspaceEventsFilterRequest.ts
  src/models/api/workspaceEventsHistoryRequest.ts
  src/models/workspaceEvent.ts
  src/models/workspaceEvents.ts
  src/models/workspaceEventsCount.ts
  src/services/workspaceEventsApi.ts
  src/types/index.ts
  src/types/workspaceEventsFilter.ts
  src/types/workspaceEventsHistory.ts
  src/utilities/api.ts
  src/utilities/events.ts
Labels: maintenance

#2369 Move and export some compositions and export missing type
  src/compositions/index.ts
  src/compositions/useWorkspaceEvent.ts
  src/compositions/useWorkspaceEventsSubscription.ts
  src/types/index.ts
Labels: maintenance

#2372 export the events models
  src/models/index.ts
  src/models/workspaceEvent.ts
Labels: maintenance

#2380 Move custom event trigger ui over from cloud and related event comboboxes
  src/automations/components/AutomationTriggerCustomEventInput.vue
  src/automations/components/index.ts
  src/components/EventResourceCombobox.vue
  src/components/EventsCombobox.vue
  src/components/index.ts
Labels: maintenance

#2389 Move over automation logic for default values
  src/automations/components/AutomationTriggerCustomInput.vue
  src/automations/components/AutomationTriggerEventInput.vue
  src/automations/components/index.ts
  src/automations/defaultActionValues.ts
  src/automations/defaultTriggerValues.ts
  src/automations/index.ts
  src/automations/types/triggerTemplates.ts
Labels: maintenance

#2391 Move the logic for trigger labels and checks from cloud
  src/automations/types/triggerTemplates.ts
  src/automations/types/triggers.ts
Labels: maintenance

#2393 Move automation menu, toggle, and trigger description components
  src/automations/components/AutomationMenu.vue
  src/automations/components/AutomationToggle.vue
  src/automations/components/AutomationTriggerDescription.vue
  src/automations/components/AutomationsPageEmptyState.vue
  src/automations/components/index.ts
  src/localization/locale/en.ts
  src/services/WorkspaceAutomationsApi.ts
Labels: maintenance

#2416 Enhancement: Deployments counts by flow
  src/components/DeploymentsCount.vue
  src/components/FlowList.vue
  src/compositions/useDeploymentsCount.ts
  src/models/api/UiDeploymentsCountsByFlow.ts
  src/models/api/index.ts
  src/services/UiApi.ts
Labels: blocked

#2414 enhancement: Adding UI for variables of any json type
  src/components/VariableCreateModal.vue
  src/components/VariableDisplayPreview.vue
  src/components/VariableEditModal.vue
  src/components/VariablesTable.vue
  src/localization/locale/en.ts
Labels: DO NOT MERGE

#2445 Move the events line chart and time interval composition from cloud
  src/components/WorkspaceEventsLineChart.vue
  src/components/index.ts
  src/compositions/index.ts
  src/compositions/useEventsTimeInterval.ts
  src/compositions/useWorkspaceEventsFilter.ts
Labels: maintenance

#2467 Fix "Show more" button on the flow runs widget
  src/components/FlowRunsAccordionContent.vue
Labels: fix

#2476 Skip populating default values when creating "Run deployment" automation actions
  src/automations/components/AutomationActionRunDeploymentParameters.vue
  src/schemas/components/SchemaFormProperty.vue
  src/schemas/components/SchemaFormPropertyAllOf.vue
  src/schemas/components/SchemaFormPropertyAnyOf.vue
  src/schemas/components/SchemaFormPropertyArray.vue
  src/schemas/components/SchemaFormPropertyMenu.vue
  src/schemas/components/SchemaInput.vue
  src/schemas/compositions/usePrefectKindValue.ts
  src/schemas/compositions/useSchema.ts
  src/schemas/compositions/useSchemaFormKinds.ts
  src/schemas/compositions/useSchemaFormSettings.ts
  src/schemas/compositions/useSchemaProperty.ts
  src/utilities/inject.ts
Labels: enhancement

#2482 Remove old schema properties from deployments
  src/automations/components/AutomationActionRunDeploymentInput.vue
  src/automations/components/AutomationActionRunDeploymentParameters.vue
  src/components/DeploymentCustomRunOverflowMenuItem.vue
  src/components/DeploymentForm.vue
  src/components/DeploymentFormV2.vue
  src/components/DeploymentQuickRunOverflowMenuItem.vue
  src/components/DeploymentToggle.vue
  src/components/FlowRunCreateFormV2.vue
  src/components/ParametersTable.vue
  src/components/QuickRunParametersModal.vue
  src/components/index.ts
  src/maps/deployment.ts
  src/maps/index.ts
  src/mocks/deployment.ts
  src/models/Deployment.ts
  src/models/DeploymentFlowRunCreate.ts
  src/models/DeploymentUpdate.ts
  src/models/api/DeploymentResponse.ts
  src/services/WorkspaceDeploymentsApi.ts
  src/utilities/parameters.ts
Labels: maintenance

#2489 Remove unused deployments list component
  src/components/DeploymentsList.vue
  src/components/index.ts
Labels: maintenance
